project:
  type: website
  output-dir: docs

website:
  title: "JSM 2024 Session - Speed 6, \"Course: Statistics for Social Justice\""
  navbar:
    background: "#523178"
    right:
      - icon: github
        href: https://github.com/stats-tgeorge/SJ_stats_course_JSM24
      - icon: twitter-x
        href: https://x.com/stats_tgeorge
      - icon: person-circle
        href: https://stats-tgeorge.github.io/personal_website/about.html
      - icon: mastadon
        href: https://fosstodon.org/@stats_tgeorge


